# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignupPlus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('state', localflavor.us.models.USStateField(max_length=2, verbose_name='State')),
                ('zip_code', localflavor.us.models.USZipCodeField(max_length=10, verbose_name='Zip code')),
                ('home_phone', localflavor.us.models.PhoneNumberField(max_length=20, verbose_name='Phone number')),
                ('birth_date', models.DateField(verbose_name='BirthDate')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=20, verbose_name='Gender')),
            ],
        ),
    ]
